// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCyXwK0mYa4Wqn5EW52_EuxJXcAg_ikmJA',
    appId: '1:961000284406:web:088fe2e637c46ddd38ccd7',
    messagingSenderId: '961000284406',
    projectId: 'shop-59b51',
    authDomain: 'shop-59b51.firebaseapp.com',
    storageBucket: 'shop-59b51.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDXnG2sgj5jjePnZ6p-hOSTu36IRLQkYEY',
    appId: '1:961000284406:android:838c05b1ce2cbd0f38ccd7',
    messagingSenderId: '961000284406',
    projectId: 'shop-59b51',
    storageBucket: 'shop-59b51.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBSXeICefFINYFeANZ_nOGPjOet4rRblOU',
    appId: '1:961000284406:ios:d1c94db5bb581c5c38ccd7',
    messagingSenderId: '961000284406',
    projectId: 'shop-59b51',
    storageBucket: 'shop-59b51.firebasestorage.app',
    iosBundleId: 'com.example.shop',
  );
}
